# Render configuration file for backend service
services:
  - type: web
    name: the-deployment-api
    runtime: node
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: chmod +x healthcheck.sh && node server.js
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - fromGroup: the-deployment-env
    autoDeploy: true
    # CORS Headers explicitly set in Render
    headers:
      - path: /*
        name: Access-Control-Allow-Origin
        value: https://shivamstracker.netlify.app
      - path: /*
        name: Access-Control-Allow-Methods
        value: GET, POST, PUT, DELETE, PATCH, OPTIONS
      - path: /*
        name: Access-Control-Allow-Headers
        value: Origin, X-CSRF-Token, X-Requested-With, Accept, Accept-Version, Content-Length, Content-MD5, Content-Type, Date, X-Api-Version, Authorization
      - path: /*
        name: Access-Control-Allow-Credentials
        value: "true"
      - path: /*
        name: Access-Control-Max-Age
        value: "86400"
